PyShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('user_profile.urls', namespace='user_profile')),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('api/v1/', include('productsAPI.urls', namespace='productsAPI')),
    path('', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
]

user_profile/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

app_name = 'user_profile'


urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', LogoutView.as_view(), name='user_logout'),
    path('signup/', views.UserRegistrationView.as_view(), name='user_registration'),
    path('profile/update/', views.UserProfileView.as_view(), name='profile_update'),
    path('profile/', views.UserAccountView.as_view(), name='user_profile')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}My shop{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body style="display: flex; flex-direction: column" >
<div id="header">
    <div>
        <a href="/" class="logo">My shop</a>
    </div>
    <div>
        {% if user.is_authenticated %}
            <span id="hello">Hello, <a href="{% url 'user_profile:user_profile' %}">
                {% if user.first_name %}{{ user.first_name }}{% else %}{{ user.username }}{% endif %}.
                </a>
            </span>
            <a href="{% url 'user_profile:user_logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'user_profile:user_login' %}">Login</a>
        {% endif %}
    </div>
</div>
<div id="subheader">
    <div class="cart">
        {% with total_items=cart|length %}
            {% if cart|length > 0 %}
                Your cart:
                <a href="{% url 'cart:cart_detail' %}">
                {{ total_items }} item{{ total_items|pluralize }},
                ${{ cart.get_total_price }}
                </a>
                {% else %}
                Your cart is empty.
            {% endif %}
        {% endwith %}
    </div>
</div>
<div id="content">
    {% block content %}{% endblock %}
</div>
<nav style="flex: 0 0 auto; margin: 0 auto;">
    {% block paginator %}{% endblock paginator %}
</nav>
{% if user.is_staff %}
<div class="admin-panel">
    <a href="/admin/" class="btn btn-primary">Admin</a>
</div>
{% endif %}
</body>
</html>